### ISSUE TITLE
Wrong order in CSV file

### ISSUE THREAD

**Issue by BastienClermont** [lukearran/TvTimeToTrakt#1]
Hi, Thanks for this amazing script! Just to let you know that TV Time probably changed the order of the columns in which the watched episodes are saved. I noticed when I got a date parsing error for the Tweet ID column.

Now the correct row number should be as following in line 317:
`

            tvShowName = row[6]
            
            # Ignore the header row
            if tvShowName != "tv_show_name":
                # Get the TV Time Episode Id
                tvShowEpisodeId = row[1]
                # Get the TV Time Season Number
                tvShowSeasonNo = row[7]
                # Get the TV Time Episode Number
                tvShowEpisodeNo = row[8]
                # Get the date which the show was marked 'watched' in TV Time
                tvShowDateWatched = row[4]
                # Parse the watched date value into a Python type
                tvShowDateWatchedConverted = datetime.strptime(
                    tvShowDateWatched, '%Y-%m-%d %H:%M:%S')`

**Comment by lukearran** [comment]
Thanks for letting me know!

Just pushed the fixed.

Kind Regards

Luke
