### ISSUE TITLE
How can i import movie data to trakt?

### ISSUE THREAD

**Issue by MuhammadBayiz** [lukearran/TvTimeToTrakt#11]
Hi is there any way to import movies too? I just see TV shows importing

**Comment by lukearran** [comment]
No, sorry - movies aren't supported yet.

I don't actively maintain this repository any more. So it's unlikely it will be implemented unless someone contributes.

Kindest Regards

Luke

**Comment by SinTan1729** [comment]
The PR #17 adds support for movies. Until that's merged, you can use [my fork](https://github.com/SinTan1729/TvTimeToTrakt/).
