### ISSUE TITLE
Manual input shows when multiple available not added at all

### ISSUE THREAD

**Issue by ksmrekar** [lukearran/TvTimeToTrakt#35]
I noticed this issue where the script seems to be lagging since it's not outputting anything. After a while it started to log again but it jumped quite in the percentage so I assumed something went wrong. Checked my TV Time csv and looked on the rows where it "lagged" and it turns out it was always on the shows I had to manually input which one to import. 

I dug a bit in the code and it seems there is an error in `searcher.py` line `204`. It checks `if skip_show is None` instead of `False`. I'm not sure if this is because of my python version (I'm using 3.9.5) and if in newer version False is considered None (I know C++ does this, but don't recall python having it like this). `skip_show` is `False` for those shows so I'm presumming this is a coding error. I changed it on my side and now all my show synced with no problem. 

Thanks for making this script you've saved me!

**Comment by mindtakerr** [comment]
Thank you for posting about this, @ksmrekar! I had the same bug and your fix worked for me as well!

**Comment by seaque** [comment]
> Thank you for posting about this, @ksmrekar! I had the same bug and your fix worked for me as well!
> 
> Although... now I see that it actually adds the wrong one, which based on other issues, appears to be a problem of the Trakt module. Maybe the check was set to None so that it doesn't accidentally tag the wrong data.

That's the most severe issue of this script, you select the right option but Trakt gets the wrong one. #15
