### ISSUE TITLE
Script Update?

### ISSUE THREAD

**Issue by rothnd** [lukearran/TvTimeToTrakt#37]
Hello,

I found your script a couple weeks ago. Just got my data from TV Time today. Fired up this script and am getting errors like it’s too outdated for my Python install (3.8.6 on macOS). Could you possibly assist with this? Thank you!
![Screenshot 2024-01-11 at 20 40 46](https://github.com/lukearran/TvTimeToTrakt/assets/150165406/0f423b1e-e0f3-4bed-bdfa-3dc3404a916e)

**Comment by bambibol** [comment]
I'm having the exact same issue here:

```
bambi@MacBook-Pro-van-Bambi-15 TvTimeToTrakt-main % python3 TimeToTrakt.py                    
Traceback (most recent call last):
  File "TimeToTrakt.py", line 12, in <module>
    from processor import TVShowProcessor, MovieProcessor
  File "/Users/bambiboland/Downloads/TvTimeToTrakt-main/processor.py", line 12, in <module>
    from searcher import TVShowSearcher, MovieSearcher, TraktTVShow, TraktMovie, TraktItem, TVTimeItem, TVTimeTVShow, \
  File "/Users/bambiboland/Downloads/TvTimeToTrakt-main/searcher.py", line 22, in <module>
    class Title:
  File "/Users/bambiboland/Downloads/TvTimeToTrakt-main/searcher.py", line 49, in Title
    def items_with_same_name(self, items: list[TraktItem]) -> list[TraktItem]:
TypeError: 'type' object is not subscriptable

```

**Comment by bobcmusgrave** [comment]
I have been looking forward to importing all the data from TV Time to Trakt and just got the GDPR data and I too am getting the same error, "TypeError: 'type' object is not subscriptable"

I will keep checking for an update.

**Comment by bambibol** [comment]
No updates on this issue yet?

**Comment by L11K** [comment]
Which version of Python are y'all using? 

I have 3.11 and the problem above seem to be related with [outdated python version](https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python/75202688#75202688) (below 3.9)


Make sure to update your python version and check if program is executing the proper one (in case you have multiple versions)

**Comment by bambibol** [comment]
> Which version of Python are y'all using?

Python 3.8.6 here. I just updated to 3.12 and now it's working-ish.

I retried the install requirements.txt, then "python3 TimeToTrakt.py" and instead of the immediate error I now get a list of options; picked one; got a link to authorize my Trakt; but then it's getting another error.

Seems like it's missing a file that wasn't in the folder that I got from TVtime:

`FileNotFoundError: [Errno 2] No such file or directory: 'tvtimedata/seen_episode.csv'`

I do have 'seen_episode_latest' (containing only 7 ep's) and 'seen_episode_source.csv' so I duplicated the later file and renamed it 'seen_episode', then re-ran the file. Now it's working on importing, having me double check some show titles to match the right one.

I'll report back when it's done to see if it's my complete watchlist!

**Comment by L11K** [comment]
You need seen_episode (for shows) not ANY other file, only that one.
Here is mine 
![image](https://github.com/lukearran/TvTimeToTrakt/assets/18279534/08fb7bff-d962-47f3-9745-28521fa268ff)

You are going to end up with a headache later by doing the duplication you just did.

**Comment by bambibol** [comment]
> You are going to end up with a headache later by doing the duplication you just did.

Look like it turned out ok! Doesn't seem to be missing anything :)

**Comment by L11K** [comment]
Good then. I said that because I 10000% sure you were going to end up with duplicates and that you were going to have to remove manually and it would take hours.

But if you say it turned out ok, that's great. Sorry for the overreach

**Comment by bobcmusgrave** [comment]
Sorry for delay on responding to this, I had more then one Python version installed but I got it sorted and have 3.12 and I no longer get the "subscriptable" error but I am now running into the error "json.decoder.JSONDecodeError: Invalid control character at: line 3 column 87 (char 173)". 

I see that I am missing the "seen_episode.csv" files like others are also reporting here 
https://github.com/lukearran/TvTimeToTrakt/issues/45
I got my GDPR file on March 6, after submitting my request Feb 17 2024.
