### ISSUE TITLE
KeyError while running the script

### ISSUE THREAD

**Issue by SanneBosch** [lukearran/TvTimeToTrakt#48]
![Schermafbeelding 2024-04-05 164730](https://github.com/lukearran/TvTimeToTrakt/assets/166146326/3ad00823-4726-4cb1-b053-0d3933f22ed5)

**Comment by sanjeevstunner** [comment]
![image](https://github.com/lukearran/TvTimeToTrakt/assets/42514333/fa4ec35a-0756-4dcc-a11e-e87156c853cb)

I got the same error
