### ISSUE TITLE
Error line 4

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [lukearran/TvTimeToTrakt#6]
Hello,

After running the script command, I got that:

 line 4, in <module>
    from trakt import *
ModuleNotFoundError: No module named 'trakt'

**Comment by MohamadBayz** [comment]
Same in here

**Comment by 002gRTEah3mRYH** [comment]
Please ?

**Comment by BapRx** [comment]
Did you install the required packages first? `pip install tinydb trakt`
cf: https://github.com/lukearran/TvTimeToTrakt#install-required-libraries

**Comment by ertvqbgjuy** [comment]
> Did you install the required packages first? `pip install tinydb trakt` cf: https://github.com/lukearran/TvTimeToTrakt#install-required-libraries

yes

**Comment by lukearran** [comment]
> > Did you install the required packages first? `pip install tinydb trakt` cf: https://github.com/lukearran/TvTimeToTrakt#install-required-libraries
> 
> 
> 
> yes

Let me try and reproduce this. Which OS are you running the script from (e.g Windows 11, macOS)?

**Comment by ertvqbgjuy** [comment]
> > > Did you install the required packages first? `pip install tinydb trakt` cf: https://github.com/lukearran/TvTimeToTrakt#install-required-libraries
> > 
> > 
> > yes
> 
> Let me try and reproduce this. Which OS are you running the script from (e.g Windows 11, macOS)?

WIndows 11 yh

**Comment by lukearran** [comment]
I can't reproduce this issue on a clean installation of Windows 11 with Python 3.10

Please verify that you've configured Python and Pip correctly on your local environment.

But I'll keep the issue open for anyone to report a solution in the future.

**Comment by BapRx** [comment]
Hey, you can try installing the packages using `python -m pip install tinydb trakt`, it can solve your issue if you have multiple pip versions installed.

**Comment by 002gRTEah3mRYH** [comment]
Well, still not working, I give up
