### ISSUE TITLE
Got unknown error invalid literal for int() with base 10

### ISSUE THREAD

**Issue by seaque** [lukearran/TvTimeToTrakt#63]
Since TV Time changed the format in their data files, `season_number` and `episode_number` columns have floated values that results with error in the title.

This can be fixed with changing two lines in `searcher.py` from:

https://github.com/lukearran/TvTimeToTrakt/blob/26cd599e4574f538818197deb109df985285a476/searcher.py#L110-L111

to

```python
self.season_number = int(float(row["season_number"]))
self.episode_number = int(float(row["episode_number"]))
```

I only imported a couple of shows like this. Don't know any side effects but please let me know if you encounter one.

**Comment by AdClarky** [comment]
What value is given in the CSV for season and episode numbers?
Also, do you want to make a PR for this fix?

**Comment by seaque** [comment]
> What value is given in the CSV for season and episode numbers? Also, do you want to make a PR for this fix?

They are float values. No, I don't. Anyone can search for the hotfix in issues. Maybe there could be another solution.
