### ISSUE TITLE
pytrakt.json not found

### ISSUE THREAD

**Issue by casper-rilaun** [lukearran/TvTimeToTrakt#8]
Hi mate,

First, thanks for the work, definitely useful.

I have an issue with pytrakt.json : 
`FileNotFoundError: [Errno 2] No such file or directory: 'pytrakt.json'`

I look at the py code, and indeed, line 39 you're calling it : `with open(f"{Path.home()}/.pytrakt.json") as f:`

I tried to create it manually, but I don't know what to put in.
I also put my config.json inside pytrakt.json, but nothing better.

Any ideas please ?

**Comment by koccs** [comment]
Hi @casper-rilaun 

I am just a user of the script as you and I have encountered the same error.
I was able to solve it to create the file `.pytrakt.json` and add the following content:
```
{
    "OAUTH_EXPIRES_AT": 0
}
```
This tells to the script yo have never authenticated, so it starts the auth process. After this everything worked fine.
If you don't want to add `.pytrakt.json' to your home folder then you could add it next to `TimeToTrackt.py`, but for this you have change the path where it reads from. Change line 39 to:
```
    with open(".pytrakt.json") as f:
```

I have opened a pull request which contains the fixes here: #9

**Comment by casper-rilaun** [comment]
Hi @koccs 

Now with the OAUTH_EXPIRES, everything seems to went smooth.

Thanks again !

**Comment by casper-rilaun** [comment]
Quick review, nice job, everything went smooth. 7500+ import, 0 error.
